# Usage (to create or update):
# 
# gcloud init
# gcloud auth login
# gcloud components install kubectl
# gcloud container clusters get-credentials [cluster-name] --project [Project ID]
## (http://kubernetes.io/docs/user-guide/managing-deployments/#kubectl-apply)
# kubectl apply -f .
#
#
#
# inspired from
# https://github.com/kubernetes/kubernetes/blob/d4251b2a259ad3b185e13e218b13634d627e0274/examples/guestbook/all-in-one/guestbook-all-in-one.yaml
apiVersion: v1
kind: Service
metadata:
  name: newspaper-api
  labels:
    app: newspaper
    tier: backend
    role: master
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: http
  selector:
    app: newspaper
    tier: backend
    role: master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newspaper-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: newspaper
      role: master
      tier: backend
  template:
    metadata:
      labels:
        app: newspaper
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: smarp/newspaper-api:v2.3
        resources:
        resources:
          requests:
            cpu: 400m
            memory: 400Mi
          limits:
            cpu: 750m
            memory: 640Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 38765
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 38765
          initialDelaySeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 30
        ports:
        - containerPort: 38765
          name: http
          protocol: TCP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: newspaper-api
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: newspaper-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300 # desired replicas capped to the maximum recommendation within 5 mins
      policies: # limit scale down rate, max 1 pod every 10 mins
      - type: Pods
        value: 1
        periodSeconds: 600
    scaleUp:
      stabilizationWindowSeconds: 0 # no stabilisation
      policies: # limit scale up rate, max 2 pods every min
      - type: Pods
        value: 2
        periodSeconds: 60
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: newspaper-pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: newspaper

